baseurl      = "localhost"
title        = "Blog | Hara"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  #homeSubtitle0="I am a "
  homeSubtitle = "Trader, Gambler, Programmer."  
  #homeSubtitle1=" On a day to day basis, I work with data, risk and probabilities"
  #homeSubtitle2="to come up with solutions to very chaotic systems and make some money in the process."
  #homeSubtitle3="I am very keen and passionate about data-analysis, poker, and capital markets."
  #homeSubtitle4=
  #homeSubtitle5=
  #homeSubtitle6=

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  justifyContent = true

  # Metadata mostly used in document's head
  description = ""
  keywords = "homepage, blog"
  images = [""]

  

[author]
    name="Hara|Blog"
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hara"
    subtitle = "Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Hi, I am Hara."
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
   [menu]
     [[menu.main]]
      identifier = "blog"
      name       = "[Blog]"
      url        = "/posts"
     [[menu.main]]
      identifier = "goodreads"
      name       = "[Stuff I read]"
      url        = "https://www.goodreads.com/review/list/59402251-abhishek-singh?shelf=%23ALL%23"

[params.footer]
    trademark = true
    rss = false
    copyright = false
    author = true

    topText = []
    bottomText = [
      "Made with &#10084; "
    ]